trigger:
  - main
pr:
  - main

variables:
  buildConfiguration: "Release"
  dockerfilePath: "$(Build.SourcesDirectory)/Dockerfile"
  tag: "$(Build.BuildId)"

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: "Construir a aplicação"
    jobs:
      - job: Build
        steps:
          - task: UseDotNet@2
            displayName: "Instalar .NET 8 SDK"
            inputs:
              version: "8.x"

          - task: DotNetCoreCLI@2
            displayName: "Restaurar pacotes NuGet"
            inputs:
              command: "restore"
              projects: "**/*.csproj"

          - task: DotNetCoreCLI@2
            displayName: "Compilar aplicação - $(buildConfiguration)"
            inputs:
              command: "build"
              projects: "**/*.csproj"
              arguments: "--no-restore --configuration $(buildConfiguration)"

          - task: DotNetCoreCLI@2
            displayName: "Executar testes unitários"
            inputs:
              command: "test"
              projects: "**/TechChallengeUsers.Application.Tests.csproj"
              arguments: '--configuration $(buildConfiguration) --no-build --collect "Code Coverage"'
              publishTestResults: true

          - publish: "$(Build.ArtifactStagingDirectory)"
            artifact: "drop"

  - stage: Docker
    displayName: "Construir e publicar imagem Docker"
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: Build
        steps:
          - task: Docker@2
            displayName: "Construir imagem Docker"
            condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
            inputs:
              containerRegistry: "$(dockerRegistryServiceConnection)"
              repository: "$(acrName)"
              command: "build"
              Dockerfile: "$(dockerfilePath)"
              tags: "$(tag)"

          - task: Docker@2
            displayName: Login no ACR
            inputs:
              containerRegistry: "$(dockerRegistryServiceConnection)"
              command: "login"

          - task: Docker@2
            displayName: "Publicar imagem Docker"
            condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
            inputs:
              containerRegistry: "$(dockerRegistryServiceConnection)"
              repository: "$(acrName)"
              command: "push"
              tags: $(tag)

  - stage: Deploy
    displayName: Setup kubectl
    dependsOn: Docker
    condition: succeeded()
    jobs:
      - job: Kubectl
        steps:
          - task: Kubernetes@1
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'K8S'
              command: 
              secretType: 'dockerRegistry'
              containerRegistryType: 'Azure Container Registry'
          - script: kubetcl apply -f $(Build.SourcesDirectory)/manifests/config-map.yaml
          - script: kubetcl apply -f $(Build.SourcesDirectory)/manifests/deployment.yaml
          - script: kubetcl apply -f $(Build.SourcesDirectory)/manifests/service.yaml
          - script: kubetcl apply -f $(Build.SourcesDirectory)/manifests/hpa.yaml

  - stage: Infraestructure
    displayName: "Implantar Infraestrutura New Relic"
    dependsOn: Deploy
    condition: succeeded()
    jobs:
      - job: NewRelic
        steps:
          - script: |
              docker run \
              --detach \
              --name newrelic-infra \
              --network=host \
              --cap-add=SYS_PTRACE \
              --privileged \
              --pid=host \
              --volume "/:/host:ro" \
              --volume "/var/run/docker.sock:/var/run/docker.sock" \
              --volume "newrelic-infra:/etc/newrelic-infra" \
              --env NRIA_LICENSE_KEY='$(nrKey)' \
              newrelic/infrastructure:latest
